services:
  mongo:
    restart: always
    volumes:
      - ./mongodb:/data/db
      - ./configdb:/data/configdb

  torela:
    restart: always
    networks:
      - proxy
      - default
    labels:
      - caddy=api.torela.ee
      - caddy.reverse_proxy={{upstreams 5000}}
      - caddy.reverse_proxy.lb_retries=5
      - caddy.reverse_proxy.lb_try_interval=500ms

networks:
  proxy:
    external: true
