services:
  mongo:
    restart: always
    volumes:
      - ./mongodb:/data/db
      - ./configdb:/data/configdb

  torela:
    restart: always
    networks:
      - proxy
      - default
    labels:
      - caddy=api.torela.ee
      - caddy.reverse_proxy={{upstreams 5000}}

networks:
  proxy:
    external: true
